### ISSUE TITLE
core_worker.cc:499: Failed to register worker to Raylet

### ISSUE THREAD

**Issue by TongLiu-github** [LeapLabTHU/Absolute-Zero-Reasoner#15]
Hi thanks for the work. 

I met an error when running your code. Do you know how to solve that? Thanks. 
core_worker.cc:499: Failed to register worker to Raylet: IOError: [RayletClient] Unable to register worker with raylet. Failed to read data from the socket: End of file worker_id=01000000ffffffffffffffffffffffffffffffffffffffffffffffff

**Comment by Andrewzh112** [comment]
May I know when the error occurs?

**Comment by TongLiu-github** [comment]
ray.init(address=None, runtime_env={'env_vars': {'TOKENIZERS_PARALLELISM': 'true', 'NCCL_DEBUG': 'WARN'}})

I solved this error. It comes from the failure of "raylet".

**Comment by TongLiu-github** [comment]
Thanks for your reply. 

Problematic code:
`ray.init(address=None, runtime env={'env_vars': {'TOKENIZERS PARALLELISM': 'trUe', 'NCCL DEBUG': 'WARN' }})`
If using the above code (original):
Ray cannot be successfully started with the error: 
![Image](https://github.com/user-attachments/assets/f25f626b-adfb-4eb6-848c-22d5d8cc8506) 

If using the following code that l modified:
```
os.environ["TOKENIZERS PARALLELISM"] = "true"
os.environ["NCCL DEBUG"]= "WARN"
ray.init(address=None)
```
Ray can be started. But later there is another error:  

![Image](https://github.com/user-attachments/assets/a25b49b5-3e86-439a-8dc4-bafb491ce81a)

**Comment by Andrewzh112** [comment]
hmm, try this? https://github.com/volcengine/verl/issues/491

also I usally do `ray stop` everytime I do a new run

**Comment by Andrewzh112** [comment]
Will close due to inactivity, feel free to reopen
